[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_world = "Har9vLr7WFKf1XdPZzuzNTcCXbJ1Qx9AMu9v5iMuTXPV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://falling-falling-bush.solana-devnet.discover.quiknode.pro/bb644014a6469f1607cf49a9d0e44c420341eeb8/"
wallet = "/home/roro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
